apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore
  namespace: dev
spec:
  provider:
    # (2): GCP Secret Manager
    gcpsm:
      # Auth defines the information necessary to authenticate against GCP by getting
      # the credentials from an already created Kubernetes Secret.
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: chimu-335413
    # (TODO): add more provider examples here
