apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: exsecretstore
  namespace: dev
spec:
  refreshInterval: 1h   # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: secretstore   # name of the SecretStore (or kind specified)
  target:
    name: secret-ms-ingress  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: API_HOST_MS  # name of the GCPSM secret key
    remoteRef:
      key: API_HOST_MS
  - secretKey: API_PORT_MS  # name of the GCPSM secret key
    remoteRef:
      key: API_PORT_MS
  - secretKey: AUTH_SECRET_MS_BACK_CHIMU_AUTH  # name of the GCPSM secret key
    remoteRef:
      key: AUTH_SECRET_MS_BACK_CHIMU_AUTH
  - secretKey: AUTH_SECRET_MS_BACK_TASKS  # name of the GCPSM secret key
    remoteRef:
      key: AUTH_SECRET_MS_BACK_TASKS
  - secretKey: AUTH_SECRET_MS_INGRESS  # name of the GCPSM secret key
    remoteRef:
      key: AUTH_SECRET_MS_INGRESS
  - secretKey: MONGO_CONNECTION_MS  # name of the GCPSM secret key
    remoteRef:
      key: MONGO_CONNECTION_MS
  - secretKey: MYSQL_CONNECTION_MS  # name of the GCPSM secret key
    remoteRef:
      key: MYSQL_CONNECTION_MS
  - secretKey: GOOGLE_APPLICATION_CREDENTIALS  # name of the GCPSM secret key
    remoteRef:
      key: GOOGLE_APPLICATION_CREDENTIALS
  - secretKey: MSSQL_URL  # name of the GCPSM secret key
    remoteRef:
      key: MSSQL_URL
  # - secretKey: MSSQL_URL  # name of the GCPSM secret key
  #   remoteRef:
  #     key: MSSQL_URL
  - secretKey: VPN_MTECH_HOST  # name of the GCPSM secret key
    remoteRef:
      key: VPN_MTECH_HOST
  - secretKey: VPN_MTECH_PASSWORD  # name of the GCPSM secret key
    remoteRef:
      key: VPN_MTECH_PASSWORD
  - secretKey: VPN_MTECH_PORT  # name of the GCPSM secret key
    remoteRef:
      key: VPN_MTECH_PORT
  - secretKey: VPN_MTECH_TRUSTED_CERT  # name of the GCPSM secret key
    remoteRef:
      key: VPN_MTECH_TRUSTED_CERT
  - secretKey: VPN_MTECH_USERNAME  # name of the GCPSM secret key
    remoteRef:
      key: VPN_MTECH_USERNAME
  - secretKey: MSSQL_URL_LOCAL_MTECH  # name of the GCPSM secret key
    remoteRef:
      key: MSSQL_URL_LOCAL_MTECH
  - secretKey: MYSQL_CHIMU_URL  # name of the GCPSM secret key
    remoteRef:
      key: MYSQL_CHIMU_URL
  - secretKey: BQ_DATASET_ID  # name of the GCPSM secret key
    remoteRef:
      key: BQ_DATASET_ID
  - secretKey: MSSQL_URL_MTECH  # name of the GCPSM secret key
    remoteRef:
      key: MSSQL_URL_MTECH
  - secretKey: AUTH_SECRET_MS_RECOVERY  # name of the GCPSM secret key
    remoteRef:
      key: AUTH_SECRET_MS_RECOVERY
  - secretKey: RECOVERY_URL  # name of the GCPSM secret key
    remoteRef:
      key: RECOVERY_URL


  - secretKey: AUTH_SECRET_MS_BACK_ALERTAS  # name of the GCPSM secret key
    remoteRef:
      key: AUTH_SECRET_MS_BACK_ALERTAS
  - secretKey: SENDGRID_API_KEY  # name of the GCPSM secret key
    remoteRef:
      key: SENDGRID_API_KEY
  - secretKey: SENDGRID_TEMPLATE_ID  # name of the GCPSM secret key
    remoteRef:
      key: SENDGRID_TEMPLATE_ID
  - secretKey: SENDGRID_TEMPLATE_ID_ALARM_CONTROLLER  # name of the GCPSM secret key
    remoteRef:
      key: SENDGRID_TEMPLATE_ID_ALARM_CONTROLLER
  - secretKey: SENDGRID_TEMPLATE_ID_RECOVERY  # name of the GCPSM secret key
    remoteRef:
      key: SENDGRID_TEMPLATE_ID_RECOVERY

  - secretKey: TWILIO_ACCOUNT_SID  # name of the GCPSM secret key
    remoteRef:
      key: TWILIO_ACCOUNT_SID
  - secretKey: TWILIO_AUTH_TOKEN  # name of the GCPSM secret key
    remoteRef:
      key: TWILIO_AUTH_TOKEN
  - secretKey: TWILIO_MESSAGING_SERVICE_SID  # name of the GCPSM secret key
    remoteRef:
      key: TWILIO_MESSAGING_SERVICE_SID
    
  # - secretKey: MONGO_CONNECTION_MS_DEV  # name of the GCPSM secret key
  #   remoteRef:
  #     key: MONGO_CONNECTION_MS_DEV